language: ruby
rvm:
 - 2.2
 - 2.3
 - 2.4
 - 2.5
 - 2.6
addons:
  code_climate:
    repo_token: 14b0b24d9e229d31558bae8864514edd9e120add490acb554157fd6eda3514a1
# regular test configuration
after_success:
  - bundle exec codeclimate-test-reporter
